### ISSUE TITLE
Setup a Connection to a Remote Geth Node via JSON-RPC

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/beacon-chain#17]
Hi all,

The beacon chain construct frequently interacts with the main chain for purposes of checking the current block number, checking the logs of the Validator Registration Contract, and more. it is important we can setup a connection between a beacon chain node and a remote Geth node via something like JSON-RPC.

A PR for this issue would implement a minimal system that achieves this goal.

**Comment by prestonvanloon** [comment]
We must consider the security risks of running a geth node with JSON RPC and signing abilities for arbitrary transactions.

While attaching to the local process by ipc is less convenient for development, it doesn’t (potentially) expose an open protocol for signing transactions remotely. 

Either the beacon chain process has access to the private keys and we use eth_sendRawTransaction over JSON-RPC or we use the ipc attach approach which doesn’t expose eth_sign to the whole world (potentially). I am leaning towards the former idea and never exposing eth_sign over JSON-RPC.

**Comment by rawfalafel** [comment]
The account needs to be unlocked for sign to work, so the assumption is
that the rpc endpoint’s only accessible within a trusted network.

**Comment by rauljordan** [comment]
The beacon node should not be signing any tx's on the main net @prestonvanloon @rawfalafel @terenc3t

**Comment by rauljordan** [comment]
The only pieces of functionality related to main chain interaction the beacon chain contains are:

- Fetching the latest block hash
- Fetching the latest block number
- Reading the logs from the Validator Registration Contract to check for registered validators

The deposit of 32ETH into the contract should be done external to the beacon chain repo, and it should not be a baked in piece of functionality.
